#!/bin/bash

# Quick deployment commands for VPS: 160.191.88.246
# Copy and paste these commands into your SSH session

echo "=========================================="
echo "KHOHANG-IDOSI Deployment Commands"
echo "VPS: 160.191.88.246"
echo "=========================================="
echo ""
echo "Step 1: SSH into VPS"
echo "--------------------"
echo "ssh user@160.191.88.246"
echo ""
echo "Step 2: Navigate to project directory"
echo "--------------------------------------"
echo "cd /path/to/khohang-idosi  # Update this path"
echo ""
echo "Step 3: Backup database"
echo "-----------------------"
echo "mkdir -p /opt/backups/khohang-idosi"
echo "docker compose exec -T db pg_dump -U idosi -d idosi -Fc > \"/opt/backups/khohang-idosi/backup-\$(date +%Y%m%d-%H%M%S).dump\""
echo "ls -lh /opt/backups/khohang-idosi/"
echo ""
echo "Step 4: Pull latest code"
echo "------------------------"
echo "git fetch origin"
echo "git checkout feat/add-wholesale-account-role"
echo "git pull origin feat/add-wholesale-account-role"
echo "git log --oneline -5  # Verify commits"
echo ""
echo "Step 5: Build images"
echo "--------------------"
echo "docker compose build --no-cache migrate"
echo "docker compose build --no-cache api"
echo "docker compose build --no-cache worker"
echo "docker compose build --no-cache web"
echo ""
echo "Step 6: Stop services"
echo "---------------------"
echo "docker compose stop api worker web caddy"
echo ""
echo "Step 7: Run migrations"
echo "----------------------"
echo "docker compose up migrate"
echo "docker compose logs migrate  # Check for errors"
echo ""
echo "Step 8: Verify migrations"
echo "-------------------------"
echo "docker compose exec db psql -U idosi -d idosi -c \"\\dt partner_receipts\""
echo "docker compose exec db psql -U idosi -d idosi -c \"\\dt partner_receipt_lines\""
echo ""
echo "Step 9: Start services"
echo "----------------------"
echo "docker compose up -d api worker web caddy"
echo "sleep 30  # Wait for health checks"
echo ""
echo "Step 10: Verify deployment"
echo "--------------------------"
echo "docker compose ps  # All should be healthy"
echo "docker compose logs api --tail=50"
echo "curl -k https://localhost/ready"
echo ""
echo "Step 11: Monitor"
echo "----------------"
echo "docker compose logs -f api worker  # Press Ctrl+C to stop"
echo ""
echo "=========================================="
echo "Rollback (if needed):"
echo "docker compose down"
echo "docker compose exec -T db pg_restore -U idosi -d idosi -c < /opt/backups/khohang-idosi/backup-YYYYMMDD-HHMMSS.dump"
echo "git checkout <previous-commit>"
echo "docker compose up -d"
echo "=========================================="
