import type { AllocationRequest, LedgerRow, ProductConversion, StoreHealth } from './types';

const catalogSeed: Array<[string, number, string]> = [
  ['Đầm', 3, '1.000'],
  ['Quần Jeans', 2, '1.000'],
  ['Quần dài nữ', 3, '1.000'],
  ['Chân váy', 3, '1.000'],
  ['Quần short', 4, '1.000'],
  ['Trẻ em', 6, '1.000'],
  ['Đồ đông', 1, '1.000'],
  ['Đồ bộ', 3, '1.000'],
  ['Đồ thể thao', 4, '1.000'],
  ['Áo khoác', 2, '1.000'],
  ['Áo nữ', 5, '1.000'],
  ['Đồ nam', 3, '1.000'],
  ['Nam SM', 3, '1.000'],
  ['Nữ SM', 5, '1.000'],
  ['Áo vest', 1, '1.000'],
  ['Áo dài', 2, '1.000'],
  ['Sản phẩm tiện ích', 1, '1.000'],
  ['Giày dép túi xách', 1, '1.000'],
  ['Big size', 3, '1.000'],
  ['Hàng thương hiệu', 3, '1.000'],
  ['Trẻ em SM', 6, '1.000'],
  ['Khăn lông', 2, '1.000'],
  ['Chăn, ga, bao gối, nệm gòn', 1, '3.000'],
  ['Đồ nội y mới', 4, '1.000'],
  ['Gấu bông', 2, '1.000'],
];

export const productConversions: ProductConversion[] = catalogSeed.map(
  ([name, itemQuantity, weightKilograms], index) => ({
    id: `SKU-${String(index + 1).padStart(3, '0')}`,
    name,
    itemQuantity,
    weightKilograms,
    status: 'ACTIVE',
    effectiveDate: '2026-09-12',
  }),
);

export const storeHealth: StoreHealth[] = [
  {
    code: 'NVT',
    name: 'DS Nguyễn Văn Trỗi',
    type: 'RETAIL',
    unopenedBags: 54,
    unopenedKg: 5120,
    sellingBags: 22,
    sellingKg: 1840,
    pendingSortKg: 460,
    revenueVnd: 482_000_000,
    health: 'STABLE',
  },
  {
    code: 'GV',
    name: 'Cửa hàng Gò Vấp',
    type: 'RETAIL',
    unopenedBags: 12,
    unopenedKg: 1180,
    sellingBags: 10,
    sellingKg: 980,
    pendingSortKg: 620,
    revenueVnd: 318_000_000,
    health: 'WATCH',
  },
  {
    code: 'TD',
    name: 'Cửa hàng Thủ Đức',
    type: 'RETAIL',
    unopenedBags: 38,
    unopenedKg: 3640,
    sellingBags: 14,
    sellingKg: 1260,
    pendingSortKg: 780,
    revenueVnd: 356_000_000,
    health: 'WATCH',
  },
  {
    code: 'BD',
    name: 'DS Bình Dương',
    type: 'RETAIL',
    unopenedBags: 64,
    unopenedKg: 6080,
    sellingBags: 8,
    sellingKg: 740,
    pendingSortKg: 1120,
    revenueVnd: 221_000_000,
    health: 'RISK',
  },
  {
    code: 'TN',
    name: 'SM Tây Ninh',
    type: 'RETAIL',
    unopenedBags: 42,
    unopenedKg: 4020,
    sellingBags: 18,
    sellingKg: 1540,
    pendingSortKg: 240,
    revenueVnd: 412_000_000,
    health: 'STABLE',
  },
  {
    code: 'LX',
    name: 'Khách sỉ Long Xuyên',
    type: 'WHOLESALE',
    unopenedBags: 0,
    unopenedKg: 0,
    sellingBags: 0,
    sellingKg: 0,
    pendingSortKg: 0,
    revenueVnd: null,
    health: 'STABLE',
  },
];

export const allocationRequests: AllocationRequest[] = [
  {
    id: 'YC-GV-260912-032',
    storeCode: 'GV',
    storeName: 'Cửa hàng Gò Vấp',
    product: 'Đồ nam',
    requestedBags: 5,
    allocatedBags: 3,
    waitlistedBags: 2,
    priority: 'P0B',
    status: 'OFFERED',
    submittedAt: '07:18',
  },
  {
    id: 'YC-TD-260912-018',
    storeCode: 'TD',
    storeName: 'Cửa hàng Thủ Đức',
    product: 'Áo nữ',
    requestedBags: 4,
    allocatedBags: 2,
    waitlistedBags: 2,
    priority: 'P1',
    status: 'ALLOCATED',
    submittedAt: '07:24',
  },
  {
    id: 'YC-BD-260912-011',
    storeCode: 'BD',
    storeName: 'DS Bình Dương',
    product: 'Đầm',
    requestedBags: 6,
    allocatedBags: 0,
    waitlistedBags: 6,
    priority: 'P0A',
    status: 'WAITING',
    submittedAt: '06:55',
  },
  {
    id: 'YC-LX-260912-006',
    storeCode: 'LX',
    storeName: 'Khách sỉ Long Xuyên',
    product: 'Quần Jeans',
    requestedBags: 2,
    allocatedBags: 2,
    waitlistedBags: 0,
    priority: 'P2',
    status: 'ALLOCATED',
    submittedAt: '07:42',
  },
];

export const inventoryLedger: LedgerRow[] = [
  {
    id: 'LED-1008',
    at: '12/09/2026 09:20',
    document: 'KK-GV-260912-006',
    product: 'Đầm',
    movement: 'Khui bao',
    bagsDelta: -1,
    kgDelta: -92,
    balanceKg: 1088,
  },
  {
    id: 'LED-1007',
    at: '12/09/2026 09:05',
    document: 'NH-GV-260912-032',
    product: 'Đồ nam',
    movement: 'Xác nhận thực nhận',
    bagsDelta: 5,
    kgDelta: 474,
    balanceKg: 1180,
  },
  {
    id: 'LED-1006',
    at: '12/09/2026 09:00',
    document: 'PB-260912-001',
    product: 'Đồ nam',
    movement: 'Phân bổ chính thức',
    bagsDelta: 0,
    kgDelta: 0,
    balanceKg: 706,
  },
];
